2019-08-16 16:12:10,394 ERROR: Exception on /index [GET] [in /Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/peterhychan/Desktop/flaskblog/app/routes.py", line 30, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-08-16 16:12:12,655 ERROR: Exception on /index [GET] [in /Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/peterhychan/Desktop/flaskblog/app/routes.py", line 30, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-08-16 16:12:15,063 ERROR: Exception on /index [GET] [in /Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/peterhychan/Desktop/flaskblog/app/routes.py", line 30, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-08-16 16:12:16,532 ERROR: Exception on /user/admin [GET] [in /Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/peterhychan/Desktop/flaskblog/app/routes.py", line 99, in user
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-08-16 16:12:17,954 ERROR: Exception on /explore [GET] [in /Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/peterhychan/Desktop/flaskblog/app/routes.py", line 45, in explore
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-08-16 16:16:28,436 INFO: Microblog startup [in /Users/peterhychan/Desktop/flaskblog/app/__init__.py:42]
2019-08-16 16:16:39,597 ERROR: Exception on /explore [GET] [in /Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/peterhychan/.local/share/virtualenvs/flaskblog-s-89An1C/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/peterhychan/Desktop/flaskblog/app/routes.py", line 145, in explore
    if posts.has_next else None
UnboundLocalError: local variable 'posts' referenced before assignment
